### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by Wuxiaomann** [linlany/RAPF#6]
Traceback (most recent call last):
  File "main.py", line 192, in continual_clip
    run_class_incremental(cfg, device)
  File "main.py", line 105, in run_class_incremental
    outputs, _, __, edge_sample_features = model(inputs, memory_data=sg_inputs, not_ini=not_ini, edge_sample=edge_sample, prompt=False)
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  

File "D:\papers\Class-Incremental Learning with CLIP Adaptive\RAPF-main\continual_clip\models.py", line 120, in forward
    image_features = self.encode_image(image)
File "D:\papers\Class-Incremental Learning with CLIP Adaptive\RAPF-main\continual_clip\models.py", line 105, in encode_image
    return self.visual(image)

  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\clip\model.py", line 224, in forward
    x = self.conv1(x)  # shape = [*, width, grid, grid]
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Anaconda\envs\continual_clip\lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: expected scalar type Half but found Float

**Comment by linlany** [comment]
CLIP's original pre-training weight is of type half by default, so in forward I convert the input to float16 in https://github.com/linlany/RAPF/blob/53d66dea4fc5378bf907a55130dabf208f5a70d0/continual_clip/models.py#L114. 
I can run this part of the code without errors. 
 You may have some modifications that cause there to be a mismatch between the pre-trained model weights and the input math types. 
Please check the input image type on 'models.py, line 120' and the type of model weights you are currently using.
 This is a very common problem, it is recommended to use more search engines and debugger tools.

**Comment by Wuxiaomann** [comment]
Thanks for answering the question! I understand that the problem is caused by data format. However, I successfully run it on linux while still unable to run it on windows with totally same code except for path.

**Comment by linlany** [comment]
Thank you for your interest in our work.

We haven’t tested the code on Windows yet. My guess is that the model might not be properly allocated to the GPU on Windows, or perhaps half-precision (float16) isn’t supported. It may be helpful to convert both the input data and the model to float32 and verify their device placement. 

Environmental problems are often complex and challenging to resolve :(
